<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple.proto

namespace GPBMetadata;

class Simple
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
,
simple.proto"
Simple

id (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

