//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: simple.proto

@kotlin.jvm.JvmName("-initializesimple")
inline fun simple(block: SimpleKt.Dsl.() -> kotlin.Unit): SimpleOuterClass.Simple =
  SimpleKt.Dsl._create(SimpleOuterClass.Simple.newBuilder()).apply { block() }._build()
object SimpleKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: SimpleOuterClass.Simple.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: SimpleOuterClass.Simple.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): SimpleOuterClass.Simple = _builder.build()

    /**
     * <code>uint32 id = 1;</code>
     */
    var id: kotlin.Int
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>uint32 id = 1;</code>
     */
    fun clearId() {
      _builder.clearId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun SimpleOuterClass.Simple.copy(block: SimpleKt.Dsl.() -> kotlin.Unit): SimpleOuterClass.Simple =
  SimpleKt.Dsl._create(this.toBuilder()).apply { block() }._build()

